// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMA9b6BUA1hvU5Mm1Y5b00EzPekI09vkc',
    appId: '1:591509482132:web:89b5b26f0a271bc2172281',
    messagingSenderId: '591509482132',
    projectId: 'user-feedack-001',
    authDomain: 'user-feedack-001.firebaseapp.com',
    storageBucket: 'user-feedack-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSjfmq8sczgpDGAPcnq_e1RBqLMvwqEw',
    appId: '1:591509482132:android:10df78cd0919e388172281',
    messagingSenderId: '591509482132',
    projectId: 'user-feedack-001',
    storageBucket: 'user-feedack-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeNWy7a25SHDbJE3xmNJDaAY9kz5ff_-A',
    appId: '1:591509482132:ios:e59acc4435fae6ec172281',
    messagingSenderId: '591509482132',
    projectId: 'user-feedack-001',
    storageBucket: 'user-feedack-001.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeNWy7a25SHDbJE3xmNJDaAY9kz5ff_-A',
    appId: '1:591509482132:ios:e59acc4435fae6ec172281',
    messagingSenderId: '591509482132',
    projectId: 'user-feedack-001',
    storageBucket: 'user-feedack-001.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMA9b6BUA1hvU5Mm1Y5b00EzPekI09vkc',
    appId: '1:591509482132:web:187554d21ed05ab8172281',
    messagingSenderId: '591509482132',
    projectId: 'user-feedack-001',
    authDomain: 'user-feedack-001.firebaseapp.com',
    storageBucket: 'user-feedack-001.firebasestorage.app',
  );
}
